### ISSUE TITLE
dockerfiles using outdated node & alpine versions

### ISSUE THREAD

**Issue by monotek** [Visual-Regression-Tracker/backend#184]
The dockerfiles should be updated:

api:
https://github.com/Visual-Regression-Tracker/backend/blob/master/Dockerfile#L22

migration:
https://github.com/Visual-Regression-Tracker/backend/blob/master/prisma/Dockerfile#L1

Both are still using node12.

This should be updated.
I would also suggest to extend github actions to:
* actually build the dockerfile on all sourcecodechanges
* use dependabot to keep node and docker image dependencies up to date

**Comment by paazmaya** [comment]
Fixed via #207
