### ISSUE TITLE
Update Prisma package to latest

### ISSUE THREAD

**Issue by polyvisual** [Visual-Regression-Tracker/backend#200]
The prisma client is 2 major versions out of date (vrt is on `"@prisma/client": "2.12.1"` latest version is `"prisma": "^4.11.0"`.

A useful command line switch to reset a database was introduced which makes it easy to reset a database during development https://github.com/prisma/prisma/issues/742

There might be some work to update migrations.

Any objections to updating to the latest version?

(Also there was a package rename `@prisma/cli@2.12.1: Prisma CLI package was renamed to 'prisma'. Check it out here: https://www.npmjs.com/package/prisma`)

**Comment by pashidlos** [comment]
@polyvisual not at all !
