### ISSUE TITLE
Default user is created everytime VRT is restarted, security risk generated

### ISSUE THREAD

**Issue by nextlevelbeard** [Visual-Regression-Tracker/backend#273]
Alternatively: Cannot stop default API key from being valid

1. vrt-install.sh
2. Go to app
4. Create user1
5. Logout user1
6. Login as default user (admin)
7. Go to Users
8. Promote user1 to admin
9. Logout
10. Login as user1, now admin
11. Delete default user
12. Restart the whole app (docker-compose down/up)
13. The default user is created again, generating a security risk (?) with a default API KEY

Alternatively

1. vrt-install.sh
2. Go to app
5. Login as default user (admin)
6. Go to Profile
7. Change email "foo@bar.com", password for default user as is recommended (API key not changeable)
8. Logout
11. Restart the whole app (docker-compose down/up)
12. The default user "visual-regression-tracker@example.com" is not created again due to same apikey constraint error
13. Security risk remains as API key is non changeable

**Comment by pashidlos** [comment]
@nextlevelbeard thanks for report 
default user should be created only if there are no users
seems we lost this check here https://github.com/Visual-Regression-Tracker/backend/blob/master/prisma/seed.ts#L38

**Comment by monotek** [comment]
Would be even mor nice if email, password and api key could be set by env var.
Currently, running the container in kubernetes, we have to overwrite the seed.ts via volumemount, to be able to use secure default values.

**Comment by pashidlos** [comment]
fixed in https://github.com/Visual-Regression-Tracker/backend/releases/tag/api-v5.0.6
